#!/usr/bin/env sh
# Prevent pushing unformatted code or broken tests to master
branch=$(git rev-parse --abbrev-ref HEAD)

if [ "$branch" = "master" ]; then
  echo "Running checks before pushing to master..."
  yarn format:check || exit 1
  yarn test || exit 1
fi
