name: release-assets

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Ensure Yarn classic
        run: npm i -g yarn@1.22.22

      - name: Install deps
        run: yarn install --frozen-lockfile

      - name: Build CSS
        run: yarn build:sass

      - name: Create dist
        run: |
          set -euo pipefail
          mkdir -p dist
          cp index.html dist/
          cp -r css js dist/
          if [ -f LICENSE ]; then cp LICENSE dist/; fi
          touch dist/.nojekyll

      - name: Zip artifact
        run: |
          cd dist
          zip -r ../dist.zip .

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
